export const borrowerOne =  [
    {title:"After tax salary per month"},
    {title:"Pension"},
    {title:"Family allowance"},
    {title:"Newstart allowance"},
    {title:"Partner’s income (if applicable)"},
    {title:"Child support"},
    {title:"Other government benefits"},
    {title:"Other income e.g. rental income Specify type"},
]

export const expenses = [
    {title: "Food & Groceries"},
    {title: "Home/Utilities/Whitegoods/Repairs"},
    {title: "Public Schooling/Higher Education"},
    {title: "Personal/Health Care & Pet Care"},
    {title: "Clothing/Footwear-Dependents"},
    {title: "Communication & Connectivity"},
    {title: "Insurance-House & Contents"},
    {title: "Homewares, Appliances & Furnishings"},
    {title: "Clothing/Footwear-Adult"},
    {title: "Lifestyle/Recreation/Alcohol/Sports"},
    {title: "Subscription/Membership/Expert Fees"},
    {title: "Vehicles"},
    {title: "Transport"},
    {title: "Insurance-Motor Vehicle"},
    {title: "Insurance-Health/Personal & Other"},
    {title: "Child/Spousal Maintenance"},
    {title: "Private Schooling & Tuition"},
    {title: "Gambling & Tobacco"},
    {title: "Primary Home-Land Tax & Body Corp"},
    {title: "Investment/Second Property Expenses"},
    {title: "Other"},
]

